apiVersion: v1
kind: ServiceAccount
metadata:
  name: medi
  labels:
    app.kubernetes.io/name: medi
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: medi-db-credentials
  labels:
    app.kubernetes.io/name: medi
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/medi/secrets/medi-${ENVIRONMENT}-db-credentials/versions/latest"
        path: "db-credentials.json"
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: medi-db-credentials
  labels:
    app.kubernetes.io/name: medi
spec:
  serviceAccountName: medi
  secretProviderClassName: medi-db-credentials
  secretObject:
    type: Opaque
    data:
      - sourcePath: "db-credentials.json"
        targetKey: "credentials.json"
